//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyrOp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderId { get; set; }
        public int ClientId { get; set; }
        public int TourId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int StatusID { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Status Status { get; set; }
        public virtual Tours Tours { get; set; }
    }
}
