//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TyrOp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programs
    {
        public int ProgramId { get; set; }
        public string ProgramType { get; set; }
        public string Description { get; set; }
        public int TourId { get; set; }
    
        public virtual Tours Tours { get; set; }
    }
}
